import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Bell, ChevronDown, ChevronRight, CircleHelp, CloudUpload, DollarSign, FileSpreadsheet,
  Home as HomeIcon, LayoutDashboard, MapPinned, MoreHorizontal, Search, Settings2, Store,
  Upload, Users, Zap,
} from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";
import { calculateRevenue } from "@shared/revenue";

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [fileName, setFileName] = useState<string | null>(null);
  const [activeNav, setActiveNav] = useState("Visão geral");
  const [activationRate, setActivationRate] = useState("1,00");
  const activatedLeads = 12480;
  const revenue = calculateRevenue(activatedLeads, Number(activationRate.replace(",", ".")) || 0);
  const onFile = (file?: File) => {
    if (!file) return;
    setFileName(file.name);
    toast.success("Planilha pronta para importação", { description: `${file.name} será validada antes de subir para o CRM.` });
  };
  const nav = [
    { label: "Visão geral", icon: LayoutDashboard },
    { label: "Clientes", icon: Users, count: "12.480" },
    { label: "Lojas mapeadas", icon: Store, count: "248" },
    { label: "Importações", icon: FileSpreadsheet, count: "18" },
  ];
  return (
    <div className="min-h-screen bg-[#101118] text-[#f4f4f5]">
      <aside className="fixed inset-y-0 left-0 hidden w-[254px] border-r border-white/[0.07] bg-[#15161f] px-4 py-5 lg:flex lg:flex-col">
        <div className="mb-10 flex items-center gap-3 px-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#dd2d3f] text-sm font-black tracking-[-0.15em] text-white">MX</div><div><p className="text-[15px] font-semibold tracking-wide">MAX<span className="text-[#f04455]">MOBILE</span></p><p className="text-[10px] uppercase tracking-[0.2em] text-[#72747f]">CRM OPERATIONS</p></div></div>
        <p className="mb-3 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#6d6f7b]">Workspace</p>
        <nav className="space-y-1">{nav.map(({ label, icon: Icon, count }) => <button key={label} onClick={() => setActiveNav(label)} className={`group flex w-full items-center justify-between rounded-xl px-3 py-3 text-left text-[13px] transition-all ${activeNav === label ? "bg-[#e9e7df] font-semibold text-[#191a21] shadow-[0_8px_22px_rgba(0,0,0,.14)]" : "text-[#9a9ba5] hover:bg-white/[0.05] hover:text-white"}`}><span className="flex items-center gap-3"><Icon className="h-[17px] w-[17px]" />{label}</span>{count && <span className={`text-[10px] ${activeNav === label ? "text-[#6c6d73]" : "text-[#5f616c]"}`}>{count}</span>}</button>)}</nav>
        <p className="mb-3 mt-9 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#6d6f7b]">Gestão</p>
        <nav className="space-y-1">{[{ label: "Mapeamento de lojas", icon: MapPinned }, { label: "Configurações", icon: Settings2 }].map(({ label, icon: Icon }) => <button key={label} onClick={() => toast.info("Área em preparação", { description: "Essa tela estará disponível no próximo ciclo." })} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[13px] text-[#9a9ba5] transition hover:bg-white/[0.05] hover:text-white"><Icon className="h-[17px] w-[17px]" />{label}</button>)}</nav>
        <div className="mt-auto rounded-2xl border border-white/[0.07] bg-[#1c1d27] p-4"><div className="mb-3 flex items-center justify-between"><div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#302a1c] text-[#f5bb55]"><Zap className="h-4 w-4" /></div><span className="text-[10px] font-medium text-[#a3a3ad]">HOJE</span></div><p className="text-xs font-semibold">Operação saudável</p><p className="mt-1 text-[11px] leading-relaxed text-[#858792]">Todas as importações estão sincronizadas.</p><div className="mt-3 h-1 overflow-hidden rounded-full bg-[#30313b]"><div className="h-full w-[92%] rounded-full bg-[#db3345]" /></div></div>
        <div className="mt-5 flex items-center gap-3 border-t border-white/[0.07] pt-4"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#e6b894] text-xs font-bold text-[#3b211d]">RC</div><div className="min-w-0"><p className="truncate text-xs font-semibold">Rafael Costa</p><p className="truncate text-[10px] text-[#767883]">Administrador</p></div><ChevronDown className="ml-auto h-4 w-4 text-[#747680]" /></div>
      </aside>
      <main className="min-h-screen lg:ml-[254px]">
        <header className="flex h-[76px] items-center justify-between border-b border-white/[0.07] px-5 sm:px-8"><div className="flex items-center gap-3 lg:hidden"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#dd2d3f] text-xs font-black">MX</div><span className="text-sm font-semibold">MAXMOBILE</span></div><div className="relative hidden max-w-md flex-1 md:block"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#6d6f78]" /><input className="h-10 w-full rounded-xl border border-white/[0.07] bg-[#181922] pl-10 pr-4 text-xs text-white outline-none placeholder:text-[#666873] focus:border-[#dd2d3f]/50" placeholder="Buscar cliente, loja ou importação..." /></div><div className="flex items-center gap-3"><button onClick={() => toast.info("Você está em dia", { description: "Não há novas notificações." })} className="relative rounded-lg p-2 text-[#9698a2] transition hover:bg-white/[0.06] hover:text-white"><Bell className="h-[18px] w-[18px]" /><span className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-[#df3b4d]" /></button><div className="hidden h-6 w-px bg-white/[0.08] sm:block" /><button className="flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#e6b894] text-xs font-bold text-[#3b211d]">RC</div><ChevronDown className="h-4 w-4 text-[#747680]" /></button></div></header>
        <div className="mx-auto max-w-[1450px] px-5 py-7 sm:px-8 sm:py-9">
          <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2 text-[11px] text-[#777983]"><HomeIcon className="h-3.5 w-3.5" /> / <span className="text-[#b8b9c0]">Visão geral</span></div><h1 className="text-[28px] font-semibold tracking-[-0.04em] text-[#f8f8f9] sm:text-[32px]">Bom dia, Rafael <span className="text-[#db3345]">.</span></h1><p className="mt-1.5 text-sm text-[#81838e]">Acompanhe sua operação e mantenha o CRM sempre atualizado.</p></div><Button onClick={() => inputRef.current?.click()} className="h-11 rounded-xl bg-[#df3447] px-5 text-xs font-semibold text-white shadow-[0_10px_24px_rgba(223,52,71,.22)] transition hover:bg-[#ef4557]"><Upload className="mr-2 h-4 w-4" /> Importar planilha</Button></div>
          <input ref={inputRef} type="file" accept=".csv,.xlsx,.xls" className="hidden" onChange={(e) => onFile(e.target.files?.[0])} />
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Clientes no CRM", value: "12.480", change: "+8,4%", note: "vs. mês anterior", icon: Users, tone: "red" }, { label: "Lojas mapeadas", value: "248", change: "+12", note: "novas este mês", icon: Store, tone: "gold" }, { label: "Importações este mês", value: "18", change: "+22,1%", note: "vs. mês anterior", icon: FileSpreadsheet, tone: "blue" }, { label: "Taxa de sucesso", value: "98,6%", change: "+1,2%", note: "últimos 30 dias", icon: Zap, tone: "green" }].map(({ label, value, change, note, icon: Icon, tone }) => <div key={label} className="rounded-2xl border border-white/[0.07] bg-[#181922] p-5 shadow-[0_10px_30px_rgba(0,0,0,.12)]"><div className="mb-5 flex items-start justify-between"><div><p className="text-xs text-[#858792]">{label}</p><p className="mt-2 text-[26px] font-semibold tracking-[-0.04em] text-[#f3f3f4]">{value}</p></div><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${tone === "red" ? "bg-[#3b2027] text-[#e95767]" : tone === "gold" ? "bg-[#342b1d] text-[#dcb261]" : tone === "blue" ? "bg-[#1e2e3c] text-[#66b7e8]" : "bg-[#1d332c] text-[#71d5ac]"}`}><Icon className="h-4 w-4" /></div></div><p className="text-[11px] text-[#747681]"><span className={`mr-1 font-semibold ${tone === "red" ? "text-[#ed6574]" : "text-[#71d3a9]"}`}>{change}</span>{note}</p></div>)}</div>
          <section className="mt-6 rounded-2xl border border-[#5b2d35] bg-[linear-gradient(110deg,#24191f,#181922)] p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#3b2027] text-[#ef6472]"><DollarSign className="h-5 w-5" /></div><div><p className="text-[11px] uppercase tracking-[0.16em] text-[#9b6870]">Faturamento por ativações</p><div className="mt-1 flex items-baseline gap-3"><p className="text-3xl font-semibold tracking-[-0.04em] text-white">R$ {revenue.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</p><span className="text-[11px] text-[#74d3a9]">estimado</span></div><p className="mt-1 text-[11px] text-[#858792]">{activatedLeads.toLocaleString("pt-BR")} leads ativados × valor por ativação</p></div></div><div className="flex flex-wrap items-center gap-3 rounded-xl border border-white/[0.07] bg-black/10 p-3"><div><p className="text-[10px] uppercase tracking-[0.12em] text-[#777983]">Valor por ativação</p><p className="mt-1 text-[11px] text-[#a7a8b0]">Atualize conforme o contrato</p></div><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs text-[#92939b]">R$</span><input value={activationRate} onChange={(e) => setActivationRate(e.target.value.replace(/[^\d,]/g, ""))} className="h-10 w-[92px] rounded-lg border border-white/[0.1] bg-[#161720] pl-9 pr-2 text-sm font-semibold text-white outline-none focus:border-[#df3447]" inputMode="decimal" aria-label="Valor por ativação" /></div><div className="h-9 w-px bg-white/[0.08]" /><div className="text-right"><p className="text-[10px] text-[#777983]">Ativações no período</p><p className="mt-1 text-sm font-semibold text-[#e5e5e7]">12.480</p></div></div></div></section>

          <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><section className="rounded-2xl border border-white/[0.07] bg-[#181922] p-5 sm:p-6"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-[15px] font-semibold">Atividade de clientes</h2><p className="mt-1 text-[11px] text-[#777983]">Novos registros adicionados ao CRM</p></div><button className="flex items-center gap-2 rounded-lg border border-white/[0.08] px-3 py-2 text-[11px] text-[#b2b3bb] hover:bg-white/[0.05]">Últimos 30 dias <ChevronDown className="h-3.5 w-3.5" /></button></div><div className="flex h-[190px] items-end gap-[6px] border-b border-white/[0.07] px-2 pb-0 sm:gap-3">{[34,48,42,60,52,68,55,78,67,86,72,91,82,96,88,74,82,68,76,90,70,83,94,80,88,76,68,82,98,91].map((height, i) => <div key={i} className="group relative flex h-full flex-1 items-end"><div className={`w-full rounded-t-[4px] transition-all group-hover:bg-[#f05b6a] ${i > 25 ? "bg-[#db3345]" : "bg-[#6b303a]"}`} style={{ height: `${height}%` }} />{i === 28 && <span className="absolute -top-5 left-1/2 -translate-x-1/2 text-[9px] text-[#f06c79]">1.240</span>}</div>)}</div><div className="mt-3 flex justify-between px-1 text-[10px] text-[#686a74]"><span>01 Ago</span><span>08 Ago</span><span>15 Ago</span><span>22 Ago</span><span>31 Ago</span></div></section><section className="rounded-2xl border border-white/[0.07] bg-[#181922] p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-[15px] font-semibold">Distribuição por região</h2><p className="mt-1 text-[11px] text-[#777983]">Lojas mapeadas no território</p></div><button onClick={() => setActiveNav("Mapeamento de lojas")} className="text-[#a9abb4] hover:text-white"><MoreHorizontal className="h-5 w-5" /></button></div><div className="flex items-center gap-6"><div className="relative flex h-36 w-36 shrink-0 items-center justify-center rounded-full" style={{ background: "conic-gradient(#db3345 0 36%, #d6a94e 36% 61%, #5aaed5 61% 82%, #5e9881 82% 94%, #454653 94% 100%)" }}><div className="flex h-24 w-24 items-center justify-center rounded-full bg-[#181922] text-center"><div><p className="text-xl font-semibold">248</p><p className="text-[9px] text-[#777983]">lojas</p></div></div></div><div className="min-w-0 flex-1 space-y-3">{[["Sudeste", "36%", "#db3345"], ["Sul", "25%", "#d6a94e"], ["Nordeste", "21%", "#5aaed5"], ["Centro-Oeste", "12%", "#5e9881"], ["Norte", "6%", "#454653"]].map(([name, pct, color]) => <div key={name} className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2 text-[#a8a9b1]"><i className="h-2 w-2 rounded-full" style={{ backgroundColor: color }} />{name}</span><span className="font-medium text-[#e4e4e7]">{pct}</span></div>)}</div></div></section></div>
          <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><section className="rounded-2xl border border-white/[0.07] bg-[#181922] p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-[15px] font-semibold">Últimas importações</h2><p className="mt-1 text-[11px] text-[#777983]">Acompanhe o histórico de planilhas enviadas</p></div><button onClick={() => setActiveNav("Importações")} className="flex items-center gap-1 text-[11px] font-medium text-[#e45a68] hover:text-[#ff7b87]">Ver todas <ChevronRight className="h-3.5 w-3.5" /></button></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead><tr className="border-b border-white/[0.07] text-[10px] uppercase tracking-[0.15em] text-[#666873]"><th className="pb-3 font-medium">Arquivo</th><th className="pb-3 font-medium">Data</th><th className="pb-3 font-medium">Registros</th><th className="pb-3 font-medium">Status</th><th className="pb-3"></th></tr></thead><tbody className="text-xs">{[["clientes_sp_ago.xlsx", "Hoje, 09:42", "1.248", "Concluída"], ["mapeamento_sul_31.csv", "Ontem, 17:18", "682", "Concluída"], ["base_nordeste.xlsx", "28 Ago, 14:03", "2.104", "Concluída"], ["clientes_pri_ago.csv", "27 Ago, 10:55", "—", "Revisar"]].map(([file, date, rows, status]) => <tr key={file} className="border-b border-white/[0.05] last:border-0"><td className="py-4"><span className="flex items-center gap-2.5 font-medium text-[#dedee2]"><FileSpreadsheet className="h-4 w-4 text-[#70b9d7]" />{file}</span></td><td className="py-4 text-[#858792]">{date}</td><td className="py-4 text-[#b4b5bc]">{rows}</td><td className="py-4"><Badge className={`border-0 text-[10px] font-medium ${status === "Concluída" ? "bg-[#1d342b] text-[#72d3a9]" : "bg-[#3b2d1c] text-[#e0b45e]"}`}>{status}</Badge></td><td className="py-4 text-right"><MoreHorizontal className="ml-auto h-4 w-4 text-[#686a74]" /></td></tr>)}</tbody></table></div></section><section onClick={() => inputRef.current?.click()} className="group cursor-pointer rounded-2xl border border-dashed border-[#71313b] bg-[linear-gradient(145deg,#251a20,#181922)] p-5 transition hover:border-[#df3447] sm:p-6"><div className="flex h-full min-h-[230px] flex-col items-center justify-center text-center"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-[#3b2027] text-[#ea5263] transition group-hover:scale-105"><CloudUpload className="h-6 w-6" /></div><h2 className="text-[15px] font-semibold">Suba uma nova planilha</h2><p className="mt-2 max-w-[240px] text-[11px] leading-relaxed text-[#858792]">Arraste seu arquivo aqui ou clique para selecionar. Aceitamos .XLSX, .XLS e .CSV.</p><span className="mt-5 rounded-lg bg-[#df3447] px-4 py-2 text-[11px] font-semibold text-white shadow-[0_8px_18px_rgba(223,52,71,.2)]">Selecionar arquivo</span>{fileName && <p className="mt-3 max-w-full truncate text-[10px] text-[#74d4aa]">✓ {fileName}</p>}</div></section></div>
          <div className="mt-8 flex items-center justify-between border-t border-white/[0.07] pt-5 text-[10px] text-[#666873]"><span>Última sincronização: hoje às 09:45</span><span className="flex items-center gap-1.5"><CircleHelp className="h-3.5 w-3.5" /> Precisa de ajuda?</span></div>
        </div>
      </main>
    </div>
  );
}
